name = "xerox-api"
main = "src/index.js"
compatibility_date = "2024-04-20"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "xerox-temp-storage"

[vars]
R2_ACCOUNT_ID = "3e82a26522406a8e13b931ee38fe3405"
R2_BUCKET_NAME = "xerox-temp-storage"
